/* Auto-generated by Admin Panel */

const DEFAULT_DATA = {
  "name": "Tanim",
  "heroLabel": "Materials Science & Engineering",
  "typewriterWords": [
    "Materials Engineer",
    "Problem Solver",
    "RUET Student"
  ],
  "subtitle": "B.Sc. Student at RUET · Passionate about advanced materials, nanotechnology & sustainable engineering",
  "cvLink": "#",
  "photoURL": "",
  "bio": "I am Tanim, a Materials Science and Engineering student at RUET with a deep passion for exploring the intersection of advanced materials, nanotechnology, and sustainable engineering solutions. I thrive at the boundary of science and innovation, driven by curiosity and a commitment to meaningful research.",
  "university": "RUET",
  "department": "Materials Science & Eng.",
  "year": "Undergraduate",
  "skills": [
    {
      "title": "Materials Science",
      "items": ["Crystallography", "Phase Diagrams", "Fracture"]
    },
    {
      "title": "Research & Analysis",
      "items": ["Literature Review", "Data Analysis", "Lab Techniques"]
    },
    {
      "title": "Software & Tools",
      "items": ["MATLAB", "Origin Pro", "AutoCAD", "Davinci Resolve", "MS Office"]
    },
    {
      "title": "Engineering Skills",
      "items": ["Problem Solving", "Technical Writing", "Teamwork", "Project Management", "Critical Thinking"]
    }
  ],
  "projects": [
    {
      "title": "Projects coming soon...",
      "excerpt": "Exciting projects are on the way. Check back soon!",
      "desc": "<p>Exciting projects are on the way. Check back soon!</p>",
      "tags": "Materials Science",
      "link": "#",
      "date": "",
      "status": "Ongoing"
    }
  ],
  "researchInterests": [
    "Nanomaterials and Nanotechnology",
    "Sustainable and Green Materials",
    "Energy Storage Materials"
  ],
  "publications": [],
  "email": "tanim97@proton.me",
  "github": "https://github.com/tanim-mse",
  "linkedin": "https://linkedin.com/in/",
  "researchgate": "https://researchgate.net/",
  "contactMessage": "Have a research idea, collaboration opportunity, or just want to talk materials science? I'd love to hear from you.",
  "appearance": {
    "accentColor": "#7c3aed",
    "fontSize": "17px"
  },
  "adminPassword": "275056c26a6b4fb1f5e49cd8a8e0f69f5c29b84055a6d3875be68edc820c6c75"
};

function getData() {
  try {
    const saved = localStorage.getItem('portfolioData');
    if (saved) { const parsed = JSON.parse(saved); return deepMerge(DEFAULT_DATA, parsed); }
  } catch (e) {}
  return JSON.parse(JSON.stringify(DEFAULT_DATA));
}

function saveData(data) {
  try { localStorage.setItem('portfolioData', JSON.stringify(data)); return true; } catch(e) { return false; }
}

function resetData() {
  localStorage.removeItem('portfolioData');
  return JSON.parse(JSON.stringify(DEFAULT_DATA));
}

function deepMerge(target, source) {
  const result = Object.assign({}, target);
  for (const key of Object.keys(source)) {
    if (source[key] !== null && typeof source[key] === 'object' && !Array.isArray(source[key])) {
      result[key] = deepMerge(target[key] || {}, source[key]);
    } else { result[key] = source[key]; }
  }
  return result;
}
