/* Auto-generated by Admin Panel */

const DEFAULT_DATA = {
  "name": "Tanim",
  "heroLabel": "Materials Science & Engineering",
  "typewriterWords": [
    "Materials Engineer",
    "Problem Solver",
    "RUET Student"
  ],
  "subtitle": "B.Sc. Student at RUET · Passionate about advanced materials, nanotechnology & sustainable engineering",
  "cvLink": "#",
  "photoURL": "",
  "bio": "I am Tanim, a Materials Science and Engineering student at RUET with a deep passion for exploring the intersection of advanced materials, nanotechnology, and sustainable engineering solutions. I thrive at the boundary of science and innovation, driven by curiosity and a commitment to meaningful research.",
  "university": "RUET",
  "department": "Materials Science & Eng.",
  "year": "Undergraduate",
  "skills": [
    {
      "title": "Materials Science",
      "items": [
        "Crystallography",
        "Phase Diagrams",
        "Fracture"
      ]
    },
    {
      "title": "Research & Analysis",
      "items": [
        "Literature Review",
        "Data Analysis",
        "Lab Techniques"
      ]
    },
    {
      "title": "Software & Tools",
      "items": [
        "MATLAB",
        "Origin Pro",
        "AutoCAD",
        "Davinci Resolve",
        "MS Office"
      ]
    },
    {
      "title": "Engineering Skills",
      "items": [
        "Problem Solving",
        "Technical Writing",
        "Teamwork",
        "Project Management",
        "Critical Thinking"
      ]
    }
  ],
  "projects": [
    {
      "title": "Modified Structural Design of Pit Furnace for Foundry: Mathematical Optimization for enhanced Performance",
      "excerpt": "Introduction",
      "featuredImage": "https://res.cloudinary.com/dr2b6pzux/image/upload/v1775388449/gjjhfweryrgosuk1gqdy.jpg",
      "tags": "Pit Furnace, Modified Design, Academics",
      "link": "#",
      "date": "Apr 2026",
      "status": "Ongoing",
      "blocks": [
        {
          "type": "heading1",
          "id": "a8tq7sgsuo",
          "content": "Introduction"
        },
        {
          "type": "paragraph",
          "content": "Pit furnaces are vertical crucible furnaces commonly used in foundries for melting non-ferrous metals such as aluminum. A typical design features a combustion chamber lined with refractory material, a cast-iron crucible with refractory material, a top lid with side or bottom burner(s), and a top lid with an exhaust flue. The goal of this modification is to improve thermal performance, fuel-related variables, heat transfer, operational parameters, and environmental sustainability.\nThe proposed design retains the core cylindrical geometry for uniform heat distribution but introduces multi-layer insulation, a reconfigurable refractory, and a reconfigurable refractory for waste-heat recovery, improving performance.\nscaling, and optimized dimensions. These changes are evaluated through heat balance equations and optimization to demonstrate quantifiable gains without excessive complexity.",
          "id": "u2u58ukuifj"
        },
        {
          "type": "heading1",
          "id": "yl2ohx19sw9",
          "content": "Standard vs. Proposed Design:"
        },
        {
          "type": "paragraph",
          "id": "1qh77mqfbnq",
          "content": "Standard pit furnace (e.g., square/rectangular or basic cylindrical) often uses single-layer firebrick lining (~150mm), minimal insulation (for gas only), no heat recovery, and simple burner placement. This leads to too high a wall and exhaust losses (~40-60% of input energy)."
        },
        {
          "type": "heading1",
          "id": "iuzchypy0wj",
          "content": "Proposed Modified Design (Cylindrical Pit Furnace)"
        },
        {
          "type": "image",
          "id": "m2ymva7gyk",
          "src": "https://res.cloudinary.com/dr2b6pzux/image/upload/v1775388336/ujnhu6jwwpnqihjtnhje.jpg",
          "caption": "",
          "size": "small"
        },
        {
          "type": "heading2",
          "id": "r6f58r4uojj",
          "content": "Shape and Dimension: "
        },
        {
          "type": "paragraph",
          "id": "nx8vq3m76p",
          "content": "Cylindrical (internal combustion chamber dia. ≈0.3 m, height ≈1.35 m) for reduced surface-to-volume ratio and uniform heating. Overall external diameter ≈0.4 m, total height ≈1.5 m (suitable for ~20% aluminum change, matching common foundry scales)."
        },
        {
          "type": "heading2",
          "id": "aumbeo7nr4",
          "content": "Multi-layer Lining:"
        },
        {
          "type": "paragraph",
          "id": "1lmzrh36e7d",
          "content": "i. Inner refractory (firebrick, 100 mm, high K ≈ 1.2 Wm.K for durability)\nii. Outer insulation (ceramic fiber 100 mm, low K ≈ 0.3 Wm.K for reduced conduction).\niii. Thin steel shell (2 mm)."
        },
        {
          "type": "heading2",
          "id": "pb840lurjvj",
          "content": "Recuperator:"
        },
        {
          "type": "paragraph",
          "id": "7ik1iqnba69",
          "content": "Counter-flow gas-to-air heat exchanger on the flue (effectiveness ε ≈ 0.6-0.7) to preheat combustion air."
        },
        {
          "type": "heading2",
          "id": "9qmvwoy9c1n",
          "content": "Sealing and Burner:"
        },
        {
          "type": "paragraph",
          "id": "e5unbo7xno",
          "content": "Improved lid seal (ceramic fiber gasket) to minimize leakage; optimized side burner inlet for better flame distribution and controlled excess air."
        },
        {
          "type": "heading2",
          "id": "hgcochw4q5k",
          "content": "Others: "
        },
        {
          "type": "paragraph",
          "id": "rj169nxquq",
          "content": "Bottom base reinforced; flue positioned for efficient exhaust flow."
        },
        {
          "type": "paragraph",
          "id": "mj82vbp071e",
          "content": "This cross-section illustrates the layered walls, crucible placement, sealed lid, burner inlet, recuperator, and integrated flue."
        }
      ]
    }
  ],
  "researchInterests": [
    "Nanomaterials and Nanotechnology",
    "Sustainable and Green Materials",
    "Energy Storage Materials"
  ],
  "publications": [],
  "email": "tanim97@proton.me",
  "github": "https://github.com/tanim-mse",
  "linkedin": "https://linkedin.com/in/",
  "researchgate": "https://researchgate.net/",
  "contactMessage": "Have a research idea, collaboration opportunity, or just want to talk materials science? I'd love to hear from you.",
  "appearance": {
    "accentColor": "#7c3aed",
    "fontSize": "17px"
  },
  "adminPassword": "275056c26a6b4fb1f5e49cd8a8e0f69f5c29b84055a6d3875be68edc820c6c75"
};

function getData() {
  try {
    const saved = localStorage.getItem('portfolioData');
    if (saved) { const parsed = JSON.parse(saved); return deepMerge(DEFAULT_DATA, parsed); }
  } catch (e) {}
  return JSON.parse(JSON.stringify(DEFAULT_DATA));
}

function saveData(data) {
  try { localStorage.setItem('portfolioData', JSON.stringify(data)); return true; } catch(e) { return false; }
}

function resetData() {
  localStorage.removeItem('portfolioData');
  return JSON.parse(JSON.stringify(DEFAULT_DATA));
}

function deepMerge(target, source) {
  const result = Object.assign({}, target);
  for (const key of Object.keys(source)) {
    if (source[key] !== null && typeof source[key] === 'object' && !Array.isArray(source[key])) {
      result[key] = deepMerge(target[key] || {}, source[key]);
    } else { result[key] = source[key]; }
  }
  return result;
}
